version: "2"
linters:
  enable:
    - bodyclose
    - copyloopvar
    - durationcheck
    - misspell
    - nilerr
    - prealloc
    - unconvert
    - unparam
  settings:
    errcheck:
      check-type-assertions: true
    govet:
      disable:
        - fieldalignment
      enable-all: true
    misspell:
      locale: US
    prealloc:
      simple: true
      for-loops: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
          - unparam
        path: _test\.go
      - linters:
          - unused
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 50
  max-same-issues: 5
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
