{{- if .Values.persistence.data.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "flowlens.fullname" . }}-data
  labels:
    {{- include "flowlens.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.data.accessMode }}
  {{- if .Values.persistence.data.storageClass }}
  storageClassName: {{ .Values.persistence.data.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.size }}
{{- end }}
---
{{- if .Values.persistence.captures.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "flowlens.fullname" . }}-captures
  labels:
    {{- include "flowlens.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.captures.accessMode }}
  {{- if .Values.persistence.captures.storageClass }}
  storageClassName: {{ .Values.persistence.captures.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.captures.size }}
{{- end }}
